replicaCount: 1

image:
  repository: ""
  pullPolicy: Always
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {
  prometheus.io/scrape: 'true',
  prometheus.io/path: '/metrics',
  prometheus.io/port: '80'
}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: haproxy
    haproxy.org/path-rewrite: /__CI_PROJECT_URL_PATH__/(.*) /\1
  hosts:
    - host: ""
      paths:
        - path: "/"
  tls: []

resources:
  requests:
    cpu: 100m
    memory: 190Mi
  limits:
    cpu: 600m
    memory: 1000Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

ports:
  - name: http
    containerPort: 80
    protocol: TCP

Probes:
  liveness:
    path: /liveness
    port: http
  readiness:
    path: /readiness
    port: http

EnvVars:
  APP_ENV: "dev"
  APP_NAME: "__CI_PROJECT_NAME__"
  DOTNET_ENVIRONMENT: "Development"