services:
  postgres:
    image: postgres:latest
    ports:
      - "8888:5432"
    environment:
      - POSTGRES_DB=vertical_slice_api_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres